# Generated by Django 5.2.16 on 2026-08-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OpportunityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('internship', 'Internship'), ('simulation', 'Virtual Job Simulation'), ('govt-defense', 'Govt / Defense'), ('scholarship', 'Scholarship'), ('hackathon', 'Hackathon'), ('certification', 'Certification')], default='internship', max_length=32)),
                ('organization', models.CharField(blank=True, max_length=128)),
                ('short_description', models.TextField(blank=True, help_text='The main paragraph shown on the card and post page.', max_length=2000)),
                ('apply_url', models.URLField(help_text='Real destination URL. Visitors are routed via /go/<slug>/ for tracking.')),
                ('is_exclusive', models.BooleanField(default=False, help_text='Hidden behind the Follow-on-Instagram gate. Exclusivity is a soft gate, not real access control.')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Shown at the top of the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
