# Generated by Django 5.2.17 on 2026-08-19 01:50

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alertsignup'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitypage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='The full post. Headings, lists, links, inline images and embeds are supported.'),
        ),
        migrations.AddField(
            model_name='opportunitypage',
            name='deadline',
            field=models.DateField(blank=True, help_text='Optional application deadline. The post stays listed but is tagged as missed after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='opportunitypage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Card image. Landscape fills the page top; vertical images sit left of the content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='OpportunityGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='opportunities.opportunitypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
