# Generated by Django 5.2.17 on 2026-08-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunitypage_body_opportunitypage_deadline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertSignup',
        ),
    ]
