# Generated by Django 5.2.17 on 2026-08-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_delete_alertsignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitypage',
            name='is_exclusive',
        ),
    ]
