# Generated by Django 5.2.17 on 2026-08-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_remove_opportunitypage_is_exclusive'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name (e.g. Pranav Agarkar) or role title (e.g. Technical Head).', max_length=128)),
                ('role', models.CharField(help_text='Displayed designation label below the name.', max_length=128)),
                ('department', models.CharField(blank=True, help_text="Short department tag shown on the card (e.g. 'Engineering & Tech').", max_length=64)),
                ('tier', models.CharField(choices=[('founder', 'Founder / President'), ('head', 'Department Head'), ('executive', 'Operations Executive')], default='head', help_text='Controls which section this member appears in on the team page.', max_length=16)),
                ('bio', models.TextField(blank=True, help_text='Short one- or two-sentence description shown on the card.', max_length=400)),
                ('quote', models.TextField(blank=True, help_text='Optional pull-quote (displayed only on the Founder spotlight).', max_length=500)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL. Leave blank to use @namoleads.')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL.')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first within their tier section.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this member from the public team page without deleting.')),
                ('academic_year', models.CharField(default='2026–27', help_text='Academic year label (e.g. 2026–27).', max_length=16)),
                ('photo', models.ForeignKey(blank=True, help_text='Upload a portrait photo. Will be displayed as a circle crop — square or portrait images work best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
