# Generated by Django 5.2.17 on 2026-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text='Public contact email address. Leave blank if none.', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Personal website or portfolio URL. Leave blank if none.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL. Leave blank if none (button will be hidden).'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL. Leave blank if none.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL. Leave blank if none.'),
        ),
    ]
