# Generated by Django 5.2.16 on 2026-08-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('hashed_ip', models.CharField(blank=True, max_length=64)),
                ('utm_source', models.CharField(blank=True, default='direct', max_length=32)),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='opportunities.opportunitypage')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hashed_ip', models.CharField(blank=True, max_length=64)),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='opportunities.opportunitypage')),
            ],
        ),
        migrations.CreateModel(
            name='Unlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hashed_ip', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='opportunities.opportunitypage')),
            ],
        ),
    ]
