# Generated by Django 5.2.16 on 2026-08-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlock',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlock',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='unlock',
            name='token',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
