# Generated by Django 5.2.17 on 2026-08-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_unlock_expires_at_unlock_status_unlock_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unlock',
        ),
    ]
